// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package postgres

import (
	"context"

	"github.com/0hJonny/langfuse-agents/internal/chats/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO chats.messages (session_id, parent_id, role, content, trace_id, meta_data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, parent_id, role, content, trace_id, meta_data, created_at
`

type AppendMessageParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Role      domain.MessageRole `json:"role"`
	Content   string             `json:"content"`
	TraceID   *string            `json:"trace_id"`
	MetaData  []byte             `json:"meta_data"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (ChatsMessages, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.SessionID,
		arg.ParentID,
		arg.Role,
		arg.Content,
		arg.TraceID,
		arg.MetaData,
	)
	var i ChatsMessages
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.TraceID,
		&i.MetaData,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO chats.sessions (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ChatsSessions, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Title)
	var i ChatsSessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, session_id, parent_id, role, content, trace_id, meta_data, created_at
  FROM chats.messages
 WHERE id = $1 LIMIT 1
`

// Нужен, чтобы проверить существование сообщения перед выставлением лайка/дизлайка
func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (ChatsMessages, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i ChatsMessages
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.TraceID,
		&i.MetaData,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, title, created_at, updated_at, deleted_at
  FROM chats.sessions
 WHERE id = $1 LIMIT 1
`

// Нужен для валидации прав пользователя в сервисе перед любым действием
func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (ChatsSessions, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i ChatsSessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, parent_id, role, content, trace_id, meta_data, created_at
  FROM chats.messages
 WHERE session_id = $1
 ORDER BY created_at ASC
`

func (q *Queries) GetSessionMessages(ctx context.Context, sessionID pgtype.UUID) ([]ChatsMessages, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatsMessages{}
	for rows.Next() {
		var i ChatsMessages
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Role,
			&i.Content,
			&i.TraceID,
			&i.MetaData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, title, created_at, updated_at, deleted_at
  FROM chats.sessions
 WHERE user_id = $1 AND deleted_at IS NULL
 ORDER BY updated_at DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]ChatsSessions, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatsSessions{}
	for rows.Next() {
		var i ChatsSessions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedback = `-- name: SetFeedback :one
INSERT INTO chats.feedback (message_id, rating, comment)
VALUES ($1, $2, $3)
ON CONFLICT (message_id) 
DO UPDATE SET 
    rating = EXCLUDED.rating,
    comment = EXCLUDED.comment,
    created_at = now()
RETURNING id, message_id, rating, comment, created_at
`

type SetFeedbackParams struct {
	MessageID pgtype.UUID           `json:"message_id"`
	Rating    domain.FeedbackRating `json:"rating"`
	Comment   *string               `json:"comment"`
}

// Используем ON CONFLICT, так как на message_id у нас висит UNIQUE индекс.
// Если пользователь передумает и нажмет 'dislike' вместо 'like', запись обновится.
func (q *Queries) SetFeedback(ctx context.Context, arg SetFeedbackParams) (ChatsFeedback, error) {
	row := q.db.QueryRow(ctx, setFeedback, arg.MessageID, arg.Rating, arg.Comment)
	var i ChatsFeedback
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE chats.sessions
   SET deleted_at = now()
 WHERE id = $1
`

// Вместо физического удаления ставим метку времени
func (q *Queries) SoftDeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSession, id)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE chats.sessions
   SET title = $2, updated_at = now()
 WHERE id = $1
`

type UpdateSessionTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.Exec(ctx, updateSessionTitle, arg.ID, arg.Title)
	return err
}
