// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/0hJonny/langfuse-agents/internal/chats/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatsFeedbackRating string

const (
	ChatsFeedbackRatingLike    ChatsFeedbackRating = "like"
	ChatsFeedbackRatingDislike ChatsFeedbackRating = "dislike"
)

func (e *ChatsFeedbackRating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatsFeedbackRating(s)
	case string:
		*e = ChatsFeedbackRating(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatsFeedbackRating: %T", src)
	}
	return nil
}

type NullChatsFeedbackRating struct {
	ChatsFeedbackRating ChatsFeedbackRating `json:"chats_feedback_rating"`
	Valid               bool                `json:"valid"` // Valid is true if ChatsFeedbackRating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatsFeedbackRating) Scan(value interface{}) error {
	if value == nil {
		ns.ChatsFeedbackRating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatsFeedbackRating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatsFeedbackRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatsFeedbackRating), nil
}

type ChatsMessageRole string

const (
	ChatsMessageRoleUser      ChatsMessageRole = "user"
	ChatsMessageRoleAssistant ChatsMessageRole = "assistant"
	ChatsMessageRoleSystem    ChatsMessageRole = "system"
)

func (e *ChatsMessageRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatsMessageRole(s)
	case string:
		*e = ChatsMessageRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatsMessageRole: %T", src)
	}
	return nil
}

type NullChatsMessageRole struct {
	ChatsMessageRole ChatsMessageRole `json:"chats_message_role"`
	Valid            bool             `json:"valid"` // Valid is true if ChatsMessageRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatsMessageRole) Scan(value interface{}) error {
	if value == nil {
		ns.ChatsMessageRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatsMessageRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatsMessageRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatsMessageRole), nil
}

type ChatsFeedback struct {
	ID        pgtype.UUID           `json:"id"`
	MessageID pgtype.UUID           `json:"message_id"`
	Rating    domain.FeedbackRating `json:"rating"`
	Comment   *string               `json:"comment"`
	CreatedAt pgtype.Timestamptz    `json:"created_at"`
}

type ChatsMessages struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Role      domain.MessageRole `json:"role"`
	Content   string             `json:"content"`
	TraceID   *string            `json:"trace_id"`
	MetaData  []byte             `json:"meta_data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatsSessions struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
