// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendMessage(ctx context.Context, arg AppendMessageParams) (ChatsMessages, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (ChatsSessions, error)
	// Нужен, чтобы проверить существование сообщения перед выставлением лайка/дизлайка
	GetMessageByID(ctx context.Context, id pgtype.UUID) (ChatsMessages, error)
	// Нужен для валидации прав пользователя в сервисе перед любым действием
	GetSessionByID(ctx context.Context, id pgtype.UUID) (ChatsSessions, error)
	GetSessionMessages(ctx context.Context, sessionID pgtype.UUID) ([]ChatsMessages, error)
	GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]ChatsSessions, error)
	// Используем ON CONFLICT, так как на message_id у нас висит UNIQUE индекс.
	// Если пользователь передумает и нажмет 'dislike' вместо 'like', запись обновится.
	SetFeedback(ctx context.Context, arg SetFeedbackParams) (ChatsFeedback, error)
	// Вместо физического удаления ставим метку времени
	SoftDeleteSession(ctx context.Context, id pgtype.UUID) error
	UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error
}

var _ Querier = (*Queries)(nil)
