FROM golang:1.26-alpine

# Системные зависимости
RUN apk add --no-cache git curl unzip make bash

# 1. Установка Protobuf (с автоопределением архитектуры: x86_64 или aarch64 для Apple Silicon)
ENV PROTOC_VERSION=25.1
RUN TARGET_ARCH=$(uname -m) && \
    if [ "$TARGET_ARCH" = "aarch64" ]; then PROTOC_ARCH="aarch_64"; else PROTOC_ARCH="linux-x86_64"; fi && \
    curl -LO https://github.com{PROTOC_VERSION}/protoc-${PROTOC_VERSION}-${PROTOC_ARCH}.zip \
    && unzip protoc-${PROTOC_VERSION}-${PROTOC_ARCH}.zip -d /usr/local \
    && rm protoc-${PROTOC_VERSION}-${PROTOC_ARCH}.zip

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# 2. Установка sqlc (компилируется прямо внутри Go 1.26)
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# 3. Установка golangci-lint (актуальная версия v2 с полной поддержкой Go 1.26)
RUN curl -sSfL https://githubusercontent.com | sh -s -- -b $(go env GOPATH)/bin v2.12.2

# Заглушка для удержания контейнера, пока исходный код пробрасывается через Volume
CMD [ "sleep", "infinity" ]
