// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/0hJonny/langfuse-agents/internal/auth/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUserRole string

const (
	AuthUserRoleAnonymous AuthUserRole = "anonymous"
	AuthUserRoleUser      AuthUserRole = "user"
	AuthUserRoleAdmin     AuthUserRole = "admin"
)

func (e *AuthUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthUserRole(s)
	case string:
		*e = AuthUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthUserRole: %T", src)
	}
	return nil
}

type NullAuthUserRole struct {
	AuthUserRole AuthUserRole `json:"auth_user_role"`
	Valid        bool         `json:"valid"` // Valid is true if AuthUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.AuthUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthUserRole), nil
}

type AuthUsers struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Role         domain.UserRole    `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
