// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUsers, error)
	GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error)
	UpdateUserToRegistered(ctx context.Context, arg UpdateUserToRegisteredParams) (AuthUsers, error)
}

var _ Querier = (*Queries)(nil)
