// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/0hJonny/langfuse-agents/internal/auth/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (email, password_hash, role) 
VALUES ($1, $2, $3) 
RETURNING id, email, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	Email        *string         `json:"email"`
	PasswordHash *string         `json:"password_hash"`
	Role         domain.UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUsers, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i AuthUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT a.id,
       a.email,
       a.password_hash,
       a.created_at,
       a.role 
  FROM auth.users a
WHERE a.email = $1 
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Role         domain.UserRole    `json:"role"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const updateUserToRegistered = `-- name: UpdateUserToRegistered :one
UPDATE auth.users
   SET email = $1,
       password_hash = $2,
       role = 'user',
       updated_at = CURRENT_TIMESTAMP
 WHERE id = $3
RETURNING id, email, password_hash, role, created_at, updated_at
`

type UpdateUserToRegisteredParams struct {
	Email        *string     `json:"email"`
	PasswordHash *string     `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserToRegistered(ctx context.Context, arg UpdateUserToRegisteredParams) (AuthUsers, error) {
	row := q.db.QueryRow(ctx, updateUserToRegistered, arg.Email, arg.PasswordHash, arg.ID)
	var i AuthUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
